name: Run

on:
  workflow_dispatch:
  schedule:
  - cron: "0 7 23 * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install venmo_api
        pip install python-dotenv
    - name: Run recurring Venmo(re) requests
      run: |
        python requestSpotify.py
      env:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        FRIEND_1: ${{secrets.FRIEND_1}}
        FRIEND_2: ${{secrets.FRIEND_2}}
        FRIEND_3: ${{secrets.FRIEND_3}}
        FRIEND_4: ${{secrets.FRIEND_4}}
        FRIEND_5: ${{secrets.FRIEND_5}}
        
